name: capturing
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8 # win ✓
  # firebase windows support: https://github.com/FirebaseExtended/flutterfire/discussions/5557
  # possible alternative: https://pub.dev/packages/firedart
  firebase_core: ^1.6.0 # no windows support, 6.7.21
  firebase_auth: ^3.1.0 # no windows support, 6.7.21
  firebase_storage: ^10.0.3 # no windows support, 6.7.21
  flutter_progress_hud: ^2.0.0 # win ✓
  font_awesome_flutter: ^9.1.0 # win ✓
  # see: https://github.com/Flutterando/hasura_connect/issues/90
  #hasura_connect: ^3.0.4 # win ✓
  # forked. Needs to await connect for subscription: https://github.com/Flutterando/hasura_connect/pull/99
  hasura_connect:
    git:
      url: https://github.com/barbalex/hasura_connect
      ref: master
  isar: ^0.4.0 # win ✓
  isar_flutter_libs: ^0.4.0 # win ✓
  path_provider: ^2.0.2 # win ✓
  uuid: ^3.0.4 # win ✓
  validators: ^3.0.0 # win ✓
  multi_select_flutter: ^4.0.0 # win ✓
  reorderables: ^0.4.1 # win ✓
  flutter_form_builder: ^6.0.1 # win ✓
  #form_builder_file_picker: ^1.1.0
  file_picker: ^4.0.0 # win ✓
  thumbnailer: ^2.0.0 # win ✓
  open_file: ^3.2.1 # win ?: maybe: https://github.com/crazecoder/open_file/issues/137
  recase: ^4.0.0 # win ✓
  expandable: ^5.0.1 # win ✓
  flutter_map: ^0.13.1 # win ✓
  proj4dart: ^2.0.0 # win ✓
  geolocator: ^7.6.0 # no windows support, 30.8.21
  geojson_vi: ^2.0.3 # win ✓
  geodesy: ^0.4.0-nullsafety.0 # win ✓
  flutter_map_location_marker: ^1.0.0-nullsafety.0 # no windows support, 6.7.21: https://github.com/tlserver/flutter_map_location_marker/issues/4
  #    ref: null-safety
  #flutter_map_dragmarker:
  #  git:
  #    url: https://github.com/ibrierley/flutter_map_dragmarker
  #    ref: nullsafety
  flutter_map_line_editor: # win ?
    git:
      url: https://github.com/ibrierley/flutter_map_line_editor
      ref: nullsafety
  flutter_map_marker_popup: ^1.0.1 # win ✓
  flutter_map_tappable_polyline: ^3.0.0 # win ✓
  http: ^0.13.3 # win ✓
  easy_debounce: ^2.0.1 # win ✓
  excel: ^2.0.0-null-safety-3 # win ✓
  flutter_launcher_icons: ^0.9.2 # win ✓
  flutter_layout_grid: ^1.0.3 # win ✓
  animate_do: ^2.0.0 # win ✓

# usefull if using a git too that itself uses a git version:
#dependency_overrides:
#  analyzer: 1.0.0
#  flutter_map: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^0.4.0
  build_runner: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: 'images/pen.png'
