name: capturing
description: capturing data - anytime, anywhere.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.1 # win ✓
  # firebase windows support: https://github.com/FirebaseExtended/flutterfire/discussions/5557
  # possible alternative: https://pub.dev/packages/firedart
  # use the http rest api? https://firebase.google.com/docs/reference/rest/auth
  # Now in development: https://github.com/invertase/flutterfire_desktop, https://pub.dev/packages/firebase_auth_desktop
  firebase_core: 1.13.1 # win: no, web ✓
  firebase_auth: 3.3.9 # win: no, web ✓
  firebase_auth_desktop: 0.1.1-dev.6
  firebase_core_desktop: 0.1.1-dev.3
  firebase_storage: 10.2.9 # win: no, web ✓
  flutter_progress_hud: 2.0.0 # win ✓, web ✓
  font_awesome_flutter: 9.2.0 # win ✓, web ✓
  graphql_flutter: 5.0.1 # win ✓, web: beta does? https://github.com/zino-hofmann/graphql-flutter/issues/935
  web_socket_channel: 2.1.0 # win ✓
  isar: 2.2.1 # win ✓, web ✓
  isar_flutter_libs: 2.2.1 # win ✓, web ✓
  path_provider: 2.0.9 # win ✓, web: no
  uuid: 3.0.6 # win ✓, web ✓
  validators: 3.0.0 # win ✓, web ✓
  multi_select_flutter: 4.0.0 # win ✓, web ✓
  reorderables: 0.4.3 # win ✓, web ✓
  flutter_form_builder: 7.1.1 # win ✓, web ✓
  # do not upgrade to 7.6.0, see: https://github.com/danvick/flutter_form_builder/issues/969
  form_builder_validators: 7.6.1 # win ✓, web ?
  file_picker: 4.5.0 # win ✓, web ✓
  # thumbnailer loads native_pdf_renderer which prevents windows build in v4.0.1:
  # https://github.com/rbcprolabs/packages.flutter/issues/242
  thumbnailer: 2.0.1 # win ✓, web ✓
  open_file: 3.2.1 # win, web: maybe: https://github.com/crazecoder/open_file#open_file
  recase: 4.0.0 # win ✓, web ✓
  expandable: 5.0.1 # win ✓, web ✓
  flutter_map: 0.14.0 # win ✓, web: should work, see https://github.com/fleaflet/flutter_map/issues/954
  proj4dart: 2.0.0 # win ✓, web ✓
  geolocator: 8.2.0 # win ✓, web ✓
  geojson_vi: 2.0.7 # win ✓, web ✓
  geodesy: 0.4.0-nullsafety.0 # win ✓, web ✓
  flutter_map_location_marker: 3.0.2 # windows no, 26.9.21: https://github.com/tlserver/flutter_map_location_marker/issues/4. Web: no
  #    ref: null-safety
  #flutter_map_dragmarker:
  #  git:
  #    url: https://github.com/ibrierley/flutter_map_dragmarker
  #    ref: nullsafety
  flutter_map_line_editor: # win ?
    git:
      url: https://github.com/ibrierley/flutter_map_line_editor
      ref: nullsafety
  flutter_map_marker_popup: 2.1.2 # win ✓, web: no
  flutter_map_tappable_polyline: 3.1.0 # win ✓, web: no
  http: 0.13.4 # win ✓, web ✓
  easy_debounce: 2.0.2+1 # win ✓, web ✓
  excel: 2.0.0-null-safety-3 # win ✓, web ✓
  flutter_launcher_icons: 0.9.2 # win ✓, web: no, see: https://github.com/fluttercommunity/flutter_launcher_icons/issues/126
  flutter_layout_grid: 1.0.6 # win ✓, web ✓
  animate_do: 2.1.0 # win ✓, web ✓

# usefull if using a git tool that itself uses a git version:
dependency_overrides:
  latlong2: 0.8.1
  native_pdf_renderer: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: 2.2.1
  build_runner: 2.1.7
  flutter_lints: 1.0.4
  msix: 3.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: 'images/pen.png'

msix_config:
  display_name: capturing
  publisher_display_name: Gabriel Software
  identity_name: gabriel-software.productive.capturing
  msix_version: 1.0.0.1
  logo_path: C:\Users\alexa\capturing\images\pen_white.png
  capabilities: 'internetClient,location,microphone,webcam'
